### ISSUE TITLE
AnyType Crashes on ChromeOS from 0.33.17

### ISSUE THREAD

**Issue by gitiy1** [anyproto/anytype-kotlin#1744]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

Anytype would crash once updated to 0.33.17 (or higher version) or crashed after a clean install and login attempt with passwords on ChromeOS M129.

### Expected Behavior

Opened and Work Normally

### Steps To Reproduce

1. Use ChromeOS M129 
2. Turned on Android Subsystem, or ArcVM
3. Install AnyType from Google Play or use the Release APK From Github Release

### Environment

```markdown
- OS:ChromeOS 129.0.6668.112 with latest Android 13 Arcvm
- Version: from 0.33.17, the lasted working version is 0.32.41
```

### Anything else?

https://github.com/user-attachments/assets/6988fccf-7193-4c7d-817c-e22e84c6e937

![image](https://github.com/user-attachments/assets/6e9b0dec-fdea-4b1e-9be2-3534d9d60f06)
![image](https://github.com/user-attachments/assets/1cb2e63a-4a98-4601-8e06-2621bc84ea72)

If needed, I could help to try to extract the logs without rooting the device or turnning on the develop mode of ChromeOS(Android ADB has been turned on)

**Comment by uburoiubu** [comment]
@gitiy1, thanks for reporting. should be fixed in 0.33.38

**Comment by gitiy1** [comment]
> @gitiy1, thanks for reporting. should be fixed in 0.33.38

Thanks for your hard work! But still sadly, it seems like the play version and the Github Release Version(the the large apk with multi ABI) didn't work for me. To be honest, it still crashes once I opended it after install. Here is the Logcat and the system screenshot.

[crash-io-anytype-app-16_12-13-21-43_924.zip](https://github.com/user-attachments/files/18145178/crash-io-anytype-app-16_12-13-21-43_924.zip)
![image](https://github.com/user-attachments/assets/32ff8630-fcdc-4f06-9c07-9902203079bb)
![image](https://github.com/user-attachments/assets/040aee9a-ad90-46ca-b112-6ed7588a6afa)

If need further help, I could collect the logcat logs and things that adb or others that did not require root or a clean reinstall of my device😄
